name: flutter_easy_explanation
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  youtube_player_iframe: ^5.1.0  # << Add this for YouTube playlist
  url_launcher: ^6.3.2   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700